SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.SALARY,
    E.HIRE_DATE,
    D.DEPARTMENT_NAME,
    J.JOB_TITLE,
    J.MIN_SALARY     AS SALARIO_MINIMO_CARGO,
    J.MAX_SALARY     AS SALARIO_MAXIMO_CARGO
FROM HR.EMPLOYEES E
LEFT JOIN HR.DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HR.JOBS J
    ON E.JOB_ID = J.JOB_ID
WHERE E.DEPARTMENT_ID IS NOT NULL
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;